/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BattleRouteImport } from './routes/battle'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as CalculatorsRouteImport } from './routes/calculators'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DevaluationsRouteImport } from './routes/devaluations'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LoungeRouteImport } from './routes/lounge'
import { Route as MatchRouteImport } from './routes/match'
import { Route as MccRouteImport } from './routes/mcc'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as CardIdRouteImport } from './routes/card.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleRoute = BattleRouteImport.update({
  id: '/battle',
  path: '/battle',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsRoute = CalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DevaluationsRoute = DevaluationsRouteImport.update({
  id: '/devaluations',
  path: '/devaluations',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LoungeRoute = LoungeRouteImport.update({
  id: '/lounge',
  path: '/lounge',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const MccRoute = MccRouteImport.update({
  id: '/mcc',
  path: '/mcc',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const CardIdRoute = CardIdRouteImport.update({
  id: '/card/$id',
  path: '/card/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/battle': typeof BattleRoute
  '/calculator': typeof CalculatorRoute
  '/calculators': typeof CalculatorsRoute
  '/categories': typeof CategoriesRoute
  '/compare': typeof CompareRoute
  '/devaluations': typeof DevaluationsRoute
  '/explore': typeof ExploreRoute
  '/learn': typeof LearnRoute
  '/lounge': typeof LoungeRoute
  '/match': typeof MatchRoute
  '/mcc': typeof MccRoute
  '/offline': typeof OfflineRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transfers': typeof TransfersRoute
  '/wallet': typeof WalletRoute
  '/card/$id': typeof CardIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/battle': typeof BattleRoute
  '/calculator': typeof CalculatorRoute
  '/calculators': typeof CalculatorsRoute
  '/categories': typeof CategoriesRoute
  '/compare': typeof CompareRoute
  '/devaluations': typeof DevaluationsRoute
  '/explore': typeof ExploreRoute
  '/learn': typeof LearnRoute
  '/lounge': typeof LoungeRoute
  '/match': typeof MatchRoute
  '/mcc': typeof MccRoute
  '/offline': typeof OfflineRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transfers': typeof TransfersRoute
  '/wallet': typeof WalletRoute
  '/card/$id': typeof CardIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/battle': typeof BattleRoute
  '/calculator': typeof CalculatorRoute
  '/calculators': typeof CalculatorsRoute
  '/categories': typeof CategoriesRoute
  '/compare': typeof CompareRoute
  '/devaluations': typeof DevaluationsRoute
  '/explore': typeof ExploreRoute
  '/learn': typeof LearnRoute
  '/lounge': typeof LoungeRoute
  '/match': typeof MatchRoute
  '/mcc': typeof MccRoute
  '/offline': typeof OfflineRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transfers': typeof TransfersRoute
  '/wallet': typeof WalletRoute
  '/card/$id': typeof CardIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/battle'
    | '/calculator'
    | '/calculators'
    | '/categories'
    | '/compare'
    | '/devaluations'
    | '/explore'
    | '/learn'
    | '/lounge'
    | '/match'
    | '/mcc'
    | '/offline'
    | '/settings'
    | '/sitemap.xml'
    | '/transfers'
    | '/wallet'
    | '/card/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/battle'
    | '/calculator'
    | '/calculators'
    | '/categories'
    | '/compare'
    | '/devaluations'
    | '/explore'
    | '/learn'
    | '/lounge'
    | '/match'
    | '/mcc'
    | '/offline'
    | '/settings'
    | '/sitemap.xml'
    | '/transfers'
    | '/wallet'
    | '/card/$id'
  id:
    | '__root__'
    | '/'
    | '/battle'
    | '/calculator'
    | '/calculators'
    | '/categories'
    | '/compare'
    | '/devaluations'
    | '/explore'
    | '/learn'
    | '/lounge'
    | '/match'
    | '/mcc'
    | '/offline'
    | '/settings'
    | '/sitemap.xml'
    | '/transfers'
    | '/wallet'
    | '/card/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BattleRoute: typeof BattleRoute
  CalculatorRoute: typeof CalculatorRoute
  CalculatorsRoute: typeof CalculatorsRoute
  CategoriesRoute: typeof CategoriesRoute
  CompareRoute: typeof CompareRoute
  DevaluationsRoute: typeof DevaluationsRoute
  ExploreRoute: typeof ExploreRoute
  LearnRoute: typeof LearnRoute
  LoungeRoute: typeof LoungeRoute
  MatchRoute: typeof MatchRoute
  MccRoute: typeof MccRoute
  OfflineRoute: typeof OfflineRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TransfersRoute: typeof TransfersRoute
  WalletRoute: typeof WalletRoute
  CardIdRoute: typeof CardIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle': {
      id: '/battle'
      path: '/battle'
      fullPath: '/battle'
      preLoaderRoute: typeof BattleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators': {
      id: '/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof CalculatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devaluations': {
      id: '/devaluations'
      path: '/devaluations'
      fullPath: '/devaluations'
      preLoaderRoute: typeof DevaluationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lounge': {
      id: '/lounge'
      path: '/lounge'
      fullPath: '/lounge'
      preLoaderRoute: typeof LoungeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcc': {
      id: '/mcc'
      path: '/mcc'
      fullPath: '/mcc'
      preLoaderRoute: typeof MccRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/$id': {
      id: '/card/$id'
      path: '/card/$id'
      fullPath: '/card/$id'
      preLoaderRoute: typeof CardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BattleRoute: BattleRoute,
  CalculatorRoute: CalculatorRoute,
  CalculatorsRoute: CalculatorsRoute,
  CategoriesRoute: CategoriesRoute,
  CompareRoute: CompareRoute,
  DevaluationsRoute: DevaluationsRoute,
  ExploreRoute: ExploreRoute,
  LearnRoute: LearnRoute,
  LoungeRoute: LoungeRoute,
  MatchRoute: MatchRoute,
  MccRoute: MccRoute,
  OfflineRoute: OfflineRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TransfersRoute: TransfersRoute,
  WalletRoute: WalletRoute,
  CardIdRoute: CardIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
